// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf1akcu2yfyoeuA6PoVW-4M8pnpwPgabI',
    appId: '1:140241094952:android:ab246d7884acb2a54b281d',
    messagingSenderId: '140241094952',
    projectId: 'flutter-app-distribution-6d9df',
    storageBucket: 'flutter-app-distribution-6d9df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0Y8RA0NxKWIv2EHEbwD2EHaut2zCmO5s',
    appId: '1:140241094952:ios:159adf988899ebd84b281d',
    messagingSenderId: '140241094952',
    projectId: 'flutter-app-distribution-6d9df',
    storageBucket: 'flutter-app-distribution-6d9df.firebasestorage.app',
    iosBundleId: 'com.example.doctorsAppointments',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKnaEEB96PhB5kSpPuRmeRGGuo9YBB2zQ',
    appId: '1:140241094952:web:0985d8a81781e65b4b281d',
    messagingSenderId: '140241094952',
    projectId: 'flutter-app-distribution-6d9df',
    authDomain: 'flutter-app-distribution-6d9df.firebaseapp.com',
    storageBucket: 'flutter-app-distribution-6d9df.firebasestorage.app',
    measurementId: 'G-5FJE2GHB5M',
  );

}